### ISSUE TITLE
Works作成

### ISSUE THREAD

**Issue by naoki-00-ito** [INxST/st-portfolio#1]
- 横スクロール
- 横渡hoverでストーカー表示

**Comment by naoki-00-ito** [comment]
リキッドにしたほうが良さそう

https://dt-media.jp/column/liquid-font-layout

**Comment by naoki-00-ito** [comment]
基本remなので下記でも良さそう

```css
html {
  font-size: 1.6vw;
}
```
